### ISSUE TITLE
Feature tuya shutter motor control

### ISSUE THREAD

**Issue by roudee** [TheAgentK/tuya-mqtt#15]
Hi,

is it possible to control shutter motors? And if yes, which mqtt topic do i have to use? I already have all keys that I need to send the message to the correct topic. The only thing I´m missing is the right topic for this type of device.

Thanks

**Comment by TheAgentK** [comment]
Hey,
just try to use it like an socket. If the motor is also controlled via the DPS value 1, it's worth a try.
This might work. There is no topic explicitly for shutter motors yet.

In the future I will probably simplify the Topics anyway a little bit.

**Comment by roudee** [comment]
Hey,

thanks for the fast response. I already tried but got some exceptions. But I´ll give it another shot. 
Gonna post the results here afterwards.

**Comment by roudee** [comment]
I checked out the tuyapi project from codetheweb and managed to connect to the device. I can also receive data from it. But it seems to be encrypted. I´ve got the right localKey for sure. Output is this: Data from device: n\P®è¹I;;ã _Kgãª
uoÂ& ö¡.dåp'm?`

Do you know if there are any other decrypt meassures needed?

**Comment by TheAgentK** [comment]
Unfortunately I can't help, because all data is decrypted by the TuyAPI. I think an update of the TuyAPI will solve the problem.

I am currently updating the project to the latest TuyAPI version 4.0.4.
