### ISSUE TITLE
add MQTT auto discovery protocol

### ISSUE THREAD

**Issue by TheAgentK** [TheAgentK/tuya-mqtt#17]
Integration des MQTT device auto-discovery protocol von  Home Assistant. 

Auto-discovery wird hier beschrieben:
- https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html
- https://homieiot.github.io/
- https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by TheAgentK** [comment]
feature request from ticket #2

**Comment by tsightler** [comment]
Closing for now, may revisit in the future if Tuya support becomes a thing again.
