### ISSUE TITLE
Could not read from remote repository

### ISSUE THREAD

**Issue by consolacion** [TheAgentK/tuya-mqtt#27]
$   git clone git@github.com:TheAgentK/tuya-mqtt.git

Cloning into 'tuya-mqtt'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by tsightler** [comment]
I have no issues so I'm assuming you haven't yet configured any SSH keys for use with github.  You can always just use https instead of ssh:

$ git clone https://github.com/TheAgentK/tuya-mqtt.git

**Comment by consolacion** [comment]
that helped, tnx
