### ISSUE TITLE
Support for non numeric device id

### ISSUE THREAD

**Issue by francisp2** [TheAgentK/tuya-mqtt#32]
**Is your feature request related to a problem? Please describe.**
All the examples I find assume the device id is a number, e.g. 1234567890ABCDEF, however, I have two lights where the device id is not a number e.g. :  bff339668eb83f6350kkah
![lsc](https://user-images.githubusercontent.com/52328611/69225175-2bfce400-0b7e-11ea-9124-7e6b62ba58db.png)

**Describe the solution you'd like**
Don't want it to crash on the non-numeric device id

**Comment by tsightler** [comment]
I can't really think of anything in the tuya-mqtt code itself that wouldn't allow this.  The code simply accepts whatever value you put in this field and passes it to the API.  Have you tried it with things like tuya-cli and proven that it works?

**Comment by tsightler** [comment]
Did a little research and I think you may have a device that uses the v3.2 Tuya protocol.  Currently this is not supported by the Tuya API which tuya-mqtt depends on although there is an [enhancement request](https://github.com/codetheweb/tuyapi/issues/234).  Below is a small, relevant snippet:

> It's also interesting to note that some other assumptions have been broken with this protocol, for instance the devId normally consists of a prod_idx and the mac address concatenated, but here it doesn't look like a mac address at all.

Thus it wouldn't be possible to add support for this device until it is supported in tuyapi.  I will keep this open and we can revisit if/when tuyapi adds support.

**Comment by tsightler** [comment]
I don't believe that this can be supported at this time since the protocol is not supported by the API.  Closing for now.
