### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by smartnakh** [TheAgentK/tuya-mqtt#33]
**Describe the bug**
The git clone is failing

**To Reproduce**
openhabian@openhabian:/etc/openhab2/scripts $ git clone git@github.com:TheAgentK/tuya-mqtt.git
Clonage dans 'tuya-mqtt'...
Permission denied (publickey).

![image](https://user-images.githubusercontent.com/31652547/70062836-7f941680-15ef-11ea-9d6d-c9a41430e177.png)

**Comment by joncknott** [comment]
Hey @smartnakh - I was having the same issue and found that there was a solution posted in issue #27  [here](https://github.com/TheAgentK/tuya-mqtt/issues/27#issuecomment-523505537)

basically, use:

git clone https://github.com/TheAgentK/tuya-mqtt.git

instead. Worked for me - hope this helps!
