### ISSUE TITLE
How i can install it in my OpenHab2 Docker Container ?

### ISSUE THREAD

**Issue by xsasx** [TheAgentK/tuya-mqtt#38]
I have OH2 in a docker container - how i can use your stuff in there ?

**Comment by Trauma** [comment]
Build a container with this repos, run it, connect it to your mqtt browser, done. I can share a docker file if you want.

**Comment by xsasx** [comment]
@Trauma that would be great ! If this than just the tuya-mqtt without OH2 thats what im searching for !

**Comment by Trauma** [comment]
```
FROM node

RUN git clone https://github.com/TheAgentK/tuya-mqtt.git && \
         cd tuya-mqtt && \
         npm install

WORKDIR /tuya-mqtt

COPY config.json .

ENV DEBUG=*

ENTRYPOINT ["node", "tuya-mqtt.js"]
```

In this example the config is loaded in the container, you could also mount your config in the container at runtime with a host bind volume. Once deployed and connected to the mqtt broquer you can use any home automation platform.

``

**Comment by tsightler** [comment]
If I ever produce a 3.x version I will include a Dockerfile and perhaps even push an image to Docker Hub.  It's a big if though.

**Comment by member68** [comment]
So how about that docker? ;)

**Comment by Trauma** [comment]
You can use this fork, no docs but pretty straight forward... https://github.com/Trauma/tuya-mqtt
