### ISSUE TITLE
What mqtt broker

### ISSUE THREAD

**Issue by Electrik-rich546456** [TheAgentK/tuya-mqtt#66]
Hello I'm new to all this js codding so not sure if i have just missed something.
What MQTT broker mentioned [here](https://github.com/TheAgentK/tuya-mqtt#setting-up-configjson) 

Is that where the login info for the smart life app goes?
Also on a side note does anyone know why i seem to have different password for the iot.tuya dev web page and the smartlife app ?
But more importantly what mqtt info do i use ?

**Comment by tsightler** [comment]
The best answer I can give you is that you need to use the same MQTT broker that your home automation platform is using.  In general you should follow your home automations platform for setting up/using MQTT and then, once you have that working, you just connect this script to the same broker.

The Smartlife app and iot.tuya are not really related.  Although Smartlife may use iot.tuya on the back side, every OEM app for Tuya has it's own authentication system.  For example, you can use Smartlife, Tuya App, or Jinvoo (or any of a few dozen others), each having their own separate authentication.  Behind the scenes all of these use Tuya Cloud, but are OEM versions of the same app with completely separate users.  Once you sign up for iot.tuya you can even create your own personal version of the app if you are skilled enough.

**Comment by Electrik-rich546456** [comment]
Oh i see. Thanks
what if I don't use a home automation platform ?
How do I send mqtt info to my iot.tuya ?

**Comment by tsightler** [comment]
Then what's the point of using tuya-mqtt, you can just use tuya-cli to control the devices, no MQTT required.  Otherwise, just install an MQTT broker and use any MQTT client tool.  There's already tons of information available online for setting up an MQTT broker, it's just a Google (or whatever your preferred search engine is) away.
