### ISSUE TITLE
Not sure when you went into Maintenance mode

### ISSUE THREAD

**Issue by craigcurtin-dev** [TheAgentK/tuya-mqtt#72]
**!!! Please Read This First !!!**
If you are having difficulty controlling a specific device, please verify that the device works with tuya-cli prior to opening an issue here.  If you are unable to control the device via tuya-cli it will not be possible to control it with tuya-mqtt.  If the device is working with tuya-cli, please post your working commands and the equivalent commands for tuya-mqtt.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

The Tuya API project was updated with support for DP-Refresh - are you supporting this in your current implementation ?

I have done an install as of 13/5/21 and hence have the latest versions of tuyaapi and your great stuff.

I have this successfully working - but my heatpump does not send out periodic refreshes - as such i need to query it on a regular basis to see various operating parameters.

I am not a coder (can hack around bash scripts and Powershell) so can not take on maintenance of this project unfortunately. But am loving what you have done and being able to feed it into Node Red through MQTT is brilliant.

Craig

**Comment by tsightler** [comment]
It's not supported, and probably won't be.  Based on a quick glance at the implementation it doesn't look difficult to add, but as I don't have the devices and am no longer adding features to this project, unless someone else does the work and testing, it's not likely to happen.

**Comment by craigcurtin-dev** [comment]
Ok thanks for the quick response - looks like it might be time for me to learn how to code !!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by tsightler** [comment]
Closing this for now.
